language: python
python:
  - "3.6.8"
install:
  - pip install -r requirements.txt
script:
  - if [[ $TRAVIS_EVENT_TYPE == "pull_request" ]] ; then python scripts/validate_content.py --travis-repo-slug $TRAVIS_REPO_SLUG --travis-pull-request $TRAVIS_PULL_REQUEST; fi
  - if [[ $TRAVIS_EVENT_TYPE == "pull_request" ]] && [[ $TRAVIS_PULL_REQUEST_BRANCH != "master" ]] ; then scripts/dev-deploy.sh ; fi
  - if [[ $TRAVIS_EVENT_TYPE == "pull_request" ]] && [[ $TRAVIS_PULL_REQUEST_BRANCH == "master" ]] ; then scripts/prod-deploy.sh ; fi
env:
  matrix:
    secure: G2raMCI3Omackry34xIe6+ju4g64V6irWnsyeBLgWK+oVtvOUotR4p53xkLqdKceS7BE3EKfUiY2A1FF//WbtT8Dq94SF/mWUjmeHU7pAeBRb9uYKGTZocc7zPa6V2rFU+AkOLKsqDaaRGFzZDpzeJ9GZC1o/wWX6A+hmNGzWZbFZY+jqwlGw9YTCPXXH6wGvsVvUTeSXiR/t7XGsG6bgF3bIh7H8yi0seLWmrDn5RhQHZaQKoLog6kePG36awIMVGdV1YGieZ+llQhNMvNmQhUUHCUDQNVd9CTUv9oo1OBRZS4J9kJxfJvemMH+9gx1ohKsSJUJqzKew2d0pNrHQ2AF9sDESAPCjcE/evuSNbCrCrp5bfg/vIigboqV5aLaN7NrnoTq0QnhPxB/xuew0iL/Ej90k8kprJgcjQG5Kh7IEt9oLxZLZmYDCMfVQ9s61Ri+gfI/sTGplSd7DqkGN4fh5849aZKi0hV7MrDZbVsBVqhQ/E+wI5a4XWWTC2wAS/cyv/uazYEhOvUoUN4vyRdVGvJEx8N50sHRJatseHjKZPpVIi0O+xFFOxiWXZORyBM1UNpza7RVf+XhMNOqWQzfwCtOTM3DicN78J9d6muEf/kZswJvINb7C8KnDYu8VZjLQj6m7oQm9uypbQnQsI/71SV/kguARXIB9ZM2o64=
